version: 2
aliases:
  - &job_config
    docker:
      - image: jacktasia/dumb-jump-test-runner:v3
        environment:
          EVM_EMACS: $EVM_EMACS
          COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN

    working_directory: /home/travis/dumb-jump

    steps:
      - checkout
      - run: echo "$EVM_EMACS" > ~/EVM_EMACS.txt
      - restore_cache:
          keys:
            - v1-dj-cache-evm-{{ checksum "~/EVM_EMACS.txt" }}
      - run: evm install $EVM_EMACS --use --skip
      - save_cache:
          key: v1-dj-cache-evm-{{ checksum "~/EVM_EMACS.txt" }}
          paths:
            - /home/travis/.evm/
      # cask
      - restore_cache:
          keys:
            - v1-dj-cache-{{ checksum "~/EVM_EMACS.txt" }}
      - run: cask
      - save_cache:
          key: v1-dj-cache-{{ checksum "~/EVM_EMACS.txt" }}
          paths:
            - .cask/

      - run:
          name: Run Tests
          command: bash test/circleci-runner.sh

jobs:
  "emacs-24.3-travis":
    environment:
      EVM_EMACS: "emacs-24.3-travis"
    <<: *job_config

  "emacs-24.4-travis":
    environment:
      EVM_EMACS: "emacs-24.4-travis"
    <<: *job_config

  "emacs-24.5-travis":
    environment:
      EVM_EMACS: "emacs-24.5-travis"
    <<: *job_config

  "emacs-25.1-travis":
    environment:
      EVM_EMACS: "emacs-25.1-travis"
    <<: *job_config

  "emacs-25.2-travis":
    environment:
      EVM_EMACS: "emacs-25.2-travis"
    <<: *job_config

  "emacs-26.1-travis":
    environment:
      EVM_EMACS: "emacs-26.1-travis"
    <<: *job_config

workflows:
  version: 2
  build:
    jobs:
      - "emacs-24.3-travis"
      - "emacs-24.4-travis"
      - "emacs-24.5-travis"
      - "emacs-25.1-travis"
      - "emacs-25.2-travis"
      - "emacs-26.1-travis"
